image: microsoft/dotnet:2.1.500-sdk-alpine3.7

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
          - export PROJECT_NAME=Cecilifier.sln
          - export TEST_NAME=Ceciifier.Core.Tests/Cecilifier.Core.Tests.csproj
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
